// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroAcademicoApp.Server.Models;

namespace RegistroAcademicoApp.Server.Migrations
{
    [DbContext(typeof(RegistroAcademicoContext))]
    [Migration("20210320204543_addAutorizacion")]
    partial class addAutorizacion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

             
         
            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Perfil", b =>
            {
                b.Property<int>("IdPerfil")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("OpcionMenu")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("UsuarioId")
                    .HasColumnType("int");

                b.HasKey("IdPerfil");

                b.HasIndex("UsuarioId");

                b.ToTable("Perfiles");
            });


            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Perfil", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.Usuario", "UsuarioPerfil")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
