// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroAcademicoApp.Server.Models;

namespace RegistroAcademicoApp.Server.Migrations
{
    [DbContext(typeof(RegistroAcademicoContext))]
    [Migration("20210305054546_academico")]
    partial class academico
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.CuposCursos", b =>
                {
                    b.Property<int>("IdCuposCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<int?>("CursosId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdCuposCurso");

                    b.HasIndex("CursosId");

                    b.ToTable("CuposCurso");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Cursos", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurposCursoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DetRegistroAcademicoDetRegistroIdAcad")
                        .HasColumnType("int");

                    b.Property<string>("NombreCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OnLineMaestrosId")
                        .HasColumnName("onLineMaestrosId")
                        .HasColumnType("int");

                    b.Property<int?>("PresencialMaestrosId")
                        .HasColumnName("presencialMaestrosID")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("DetRegistroAcademicoDetRegistroIdAcad");

                    b.HasIndex("OnLineMaestrosId");

                    b.HasIndex("PresencialMaestrosId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.DetRegistroAcademico", b =>
                {
                    b.Property<int>("DetRegistroIdAcad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CursosId")
                        .HasColumnType("int");

                    b.Property<int?>("EncRegistroAcademicoId")
                        .HasColumnType("int");

                    b.HasKey("DetRegistroIdAcad");

                    b.HasIndex("EncRegistroAcademicoId");

                    b.ToTable("DetRegistroAcademico");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.DireccionEstudiantes", b =>
                {
                    b.Property<int>("IdDireccionEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstudianteIdEstudiante")
                        .HasColumnType("int");

                    b.HasKey("IdDireccionEstudiante");

                    b.HasIndex("EstudianteIdEstudiante");

                    b.ToTable("DireccionEstudiantes");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.EncRegistroAcademico", b =>
                {
                    b.Property<int>("IdEncRegistroAcad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DetRegId")
                        .HasColumnType("int");

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEncRegistroAcad");

                    b.HasIndex("EstudianteId");

                    b.ToTable("EncRegistroAcademcico");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("CursosCursoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultadRefId")
                        .HasColumnType("int");

                    b.Property<int>("GradoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NumeroRegistro")
                        .HasColumnType("int");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("CursosCursoId");

                    b.HasIndex("FacultadRefId");

                    b.HasIndex("GradoId");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Facultad", b =>
                {
                    b.Property<int>("FacultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultadId");

                    b.ToTable("Facultad");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Grado", b =>
                {
                    b.Property<int>("GradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GradoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradoId");

                    b.ToTable("Grado");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Maestros", b =>
                {
                    b.Property<int>("MaestroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaestroId");

                    b.ToTable("Maestros");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Seccion", b =>
                {
                    b.Property<int>("IdSeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdSeccion");

                    b.ToTable("Seccion");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.CuposCursos", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.Cursos", "CursosCupo")
                        .WithMany("CuposCurso")
                        .HasForeignKey("CursosId");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Cursos", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.DetRegistroAcademico", null)
                        .WithMany("CursosEstudiante")
                        .HasForeignKey("DetRegistroAcademicoDetRegistroIdAcad");

                    b.HasOne("RegistroAcademicoApp.Server.Models.Maestros", "OnLineMaestros")
                        .WithMany("CursosOnLineMaestros")
                        .HasForeignKey("OnLineMaestrosId");

                    b.HasOne("RegistroAcademicoApp.Server.Models.Maestros", "PresencialMaestros")
                        .WithMany("CursosPresencialMaestros")
                        .HasForeignKey("PresencialMaestrosId");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.DetRegistroAcademico", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.EncRegistroAcademico", "EncRegroAcademicoEnc")
                        .WithMany("DetRegistroAcademicosDet")
                        .HasForeignKey("EncRegistroAcademicoId");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.DireccionEstudiantes", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.Estudiante", "EstudianteIdEstudianteNavigation")
                        .WithMany("DireccionEstudiantes")
                        .HasForeignKey("EstudianteIdEstudiante");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.EncRegistroAcademico", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.Estudiante", "EstudianteReg")
                        .WithMany()
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Estudiante", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.Cursos", "CursosCurso")
                        .WithMany("Estudiante")
                        .HasForeignKey("CursosCursoId");

                    b.HasOne("RegistroAcademicoApp.Server.Models.Facultad", "FacultadRef")
                        .WithMany("Estudiante")
                        .HasForeignKey("FacultadRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroAcademicoApp.Server.Models.Grado", "Grado")
                        .WithMany("Estudiante")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
