// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroAcademicoApp.Server.Models;

namespace RegistroAcademicoApp.Server.Migrations
{
    [DbContext(typeof(RegistroAcademicoContext))]
    partial class RegistroAcademicoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

          



            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpcionMenu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMenu");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Perfiles", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdMenu")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdMenuNavigationIdMenu")
                        .HasColumnType("int");

                    b.HasKey("IdPerfil");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioIdMenuNavigationIdMenu");

                    b.ToTable("Perfiles");
                });



            modelBuilder.Entity("RegistroAcademicoApp.Server.Models.Perfiles", b =>
                {
                    b.HasOne("RegistroAcademicoApp.Server.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.HasOne("RegistroAcademicoApp.Server.Models.Menu", "UsuarioIdMenuNavigation")
                        .WithMany("Perfiles")
                        .HasForeignKey("UsuarioIdMenuNavigationIdMenu");
                });
#pragma warning restore 612, 618
        }
    }
}
